name: Docker Image CI/CD

on:
  push:
    branches: [ develop ]  # 해당 브랜치에 push 이벤트가 발생할 때만 작동

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # huggingface_token 파일 생성 (GitHub Secrets에서 받아옴)
    - name: Create huggingface_token.txt file
      run: |
        mkdir -p secrets
        echo "${{ secrets.HUGGINGFACE_TOKEN }}" > secrets/huggingface_token.txt

    # huggingface_token 디버깅용 (정상 저장 여부 확인)
    - name: Check huggingface_token.txt content
      run: cat secrets/huggingface_token.txt


    # vision-api-key 파일 생성 (GitHub Secrets에서 받아옴)
    - name: Create vision-api-key.json file
      run: |
        mkdir -p secrets
        echo "${{ secrets.VISION_API_KEY }}" | base64 -d > secrets/vision-api-key.json

    # vision-api-key 디버깅용 (정상 저장 여부 확인)
    - name: Check vision-api-key.json content
      run: cat secrets/vision-api-key.json
    
    # 현재 날짜와 커밋 해시를 환경변수로 저장
    - name: Set Docker image tags
      id: vars
      run: |
        echo "TAG_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "TAG_HASH=${GITHUB_SHA::7}" >> $GITHUB_ENV

    # DockerHub 로그인
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #Docker 이미지 빌드 & 푸시
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./deploy/docker/Dockerfile
        push: true
        tags: |
          kdykdy1/mediport-ai-server:latest
          kdykdy1/mediport-ai-server:latest-${{ env.TAG_DATE }}-${{ env.TAG_HASH }}
